const express = require('express')
const router = express.Router()
const { verifyToken, verifyRole } = require('../middleware/authMiddleware')
const authorController = require('../controller/authorController')
router.get('/all', authorController.getAllAuthor)
router.get('/:id', authorController.getAuthorById)
router.post('/',verifyToken,verifyRole(['admin', 'employee']), authorController.createAuthor)
router.put('/:id',verifyToken,verifyRole(['admin', 'employee']), authorController.updateAuthor)
router.delete('/:id', verifyToken, verifyRole(['admin']), authorController.deleteAuthor)
module.exports = router